// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// assoc_cpp
Rcpp::NumericVector assoc_cpp(Rcpp::NumericVector xR, Rcpp::NumericVector yR, double conf_level);
RcppExport SEXP _DescToolsX_assoc_cpp(SEXP xRSEXP, SEXP yRSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type xR(xRSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type yR(yRSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(assoc_cpp(xR, yR, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// brier_boot_cpp
arma::vec brier_boot_cpp(const arma::vec& resp, const arma::vec& pred, int R, bool scaled);
RcppExport SEXP _DescToolsX_brier_boot_cpp(SEXP respSEXP, SEXP predSEXP, SEXP RSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type resp(respSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pred(predSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(brier_boot_cpp(resp, pred, R, scaled));
    return rcpp_result_gen;
END_RCPP
}
// condis_pairs_tab_cpp
List condis_pairs_tab_cpp(IntegerMatrix x);
RcppExport SEXP _DescToolsX_condis_pairs_tab_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(condis_pairs_tab_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// condis_pairs_xy_cpp
NumericVector condis_pairs_xy_cpp(NumericVector xR, NumericVector yR);
RcppExport SEXP _DescToolsX_condis_pairs_xy_cpp(SEXP xRSEXP, SEXP yRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xR(xRSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yR(yRSEXP);
    rcpp_result_gen = Rcpp::wrap(condis_pairs_xy_cpp(xR, yR));
    return rcpp_result_gen;
END_RCPP
}
// cstat_boot_cpp
NumericVector cstat_boot_cpp(NumericVector yR, NumericVector xR, int B, double alpha, int seed);
RcppExport SEXP _DescToolsX_cstat_boot_cpp(SEXP yRSEXP, SEXP xRSEXP, SEXP BSEXP, SEXP alphaSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type yR(yRSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xR(xRSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cstat_boot_cpp(yR, xR, B, alpha, seed));
    return rcpp_result_gen;
END_RCPP
}
// contcoef_table_boot_bca_cpp
List contcoef_table_boot_bca_cpp(IntegerMatrix tab, int R, unsigned int seed, bool correct, double conf_level);
RcppExport SEXP _DescToolsX_contcoef_table_boot_bca_cpp(SEXP tabSEXP, SEXP RSEXP, SEXP seedSEXP, SEXP correctSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type correct(correctSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(contcoef_table_boot_bca_cpp(tab, R, seed, correct, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// contcoef_table_cpp
double contcoef_table_cpp(IntegerMatrix tab, bool correct);
RcppExport SEXP _DescToolsX_contcoef_table_cpp(SEXP tabSEXP, SEXP correctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< bool >::type correct(correctSEXP);
    rcpp_result_gen = Rcpp::wrap(contcoef_table_cpp(tab, correct));
    return rcpp_result_gen;
END_RCPP
}
// contcoef_table_boot_cpp
NumericVector contcoef_table_boot_cpp(IntegerMatrix tab, int R, unsigned int seed, bool correct);
RcppExport SEXP _DescToolsX_contcoef_table_boot_cpp(SEXP tabSEXP, SEXP RSEXP, SEXP seedSEXP, SEXP correctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type correct(correctSEXP);
    rcpp_result_gen = Rcpp::wrap(contcoef_table_boot_cpp(tab, R, seed, correct));
    return rcpp_result_gen;
END_RCPP
}
// isoWeek
IntegerVector isoWeek(DateVector x);
RcppExport SEXP _DescToolsX_isoWeek(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(isoWeek(x));
    return rcpp_result_gen;
END_RCPP
}
// usWeek
IntegerVector usWeek(DateVector x);
RcppExport SEXP _DescToolsX_usWeek(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(usWeek(x));
    return rcpp_result_gen;
END_RCPP
}
// isoYear
IntegerVector isoYear(DateVector x);
RcppExport SEXP _DescToolsX_isoYear(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(isoYear(x));
    return rcpp_result_gen;
END_RCPP
}
// isoYearweek
IntegerVector isoYearweek(DateVector x);
RcppExport SEXP _DescToolsX_isoYearweek(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(isoYearweek(x));
    return rcpp_result_gen;
END_RCPP
}
// usYearweek
IntegerVector usYearweek(DateVector x);
RcppExport SEXP _DescToolsX_usYearweek(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(usYearweek(x));
    return rcpp_result_gen;
END_RCPP
}
// usYearmonth
IntegerVector usYearmonth(DateVector x);
RcppExport SEXP _DescToolsX_usYearmonth(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(usYearmonth(x));
    return rcpp_result_gen;
END_RCPP
}
// isLeapYearDate
LogicalVector isLeapYearDate(DateVector x);
RcppExport SEXP _DescToolsX_isLeapYearDate(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(isLeapYearDate(x));
    return rcpp_result_gen;
END_RCPP
}
// isLeapYearInt
LogicalVector isLeapYearInt(IntegerVector x);
RcppExport SEXP _DescToolsX_isLeapYearInt(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(isLeapYearInt(x));
    return rcpp_result_gen;
END_RCPP
}
// top_n_cpp
Rcpp::List top_n_cpp(Rcpp::NumericVector x, int n);
RcppExport SEXP _DescToolsX_top_n_cpp(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(top_n_cpp(x, n));
    return rcpp_result_gen;
END_RCPP
}
// bottom_n_cpp
Rcpp::List bottom_n_cpp(Rcpp::NumericVector x, int n);
RcppExport SEXP _DescToolsX_bottom_n_cpp(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(bottom_n_cpp(x, n));
    return rcpp_result_gen;
END_RCPP
}
// top_i_cpp
IntegerVector top_i_cpp(NumericVector v, unsigned int n);
RcppExport SEXP _DescToolsX_top_i_cpp(SEXP vSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(top_i_cpp(v, n));
    return rcpp_result_gen;
END_RCPP
}
// bottom_i_cpp
IntegerVector bottom_i_cpp(NumericVector v, unsigned int n);
RcppExport SEXP _DescToolsX_bottom_i_cpp(SEXP vSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(bottom_i_cpp(v, n));
    return rcpp_result_gen;
END_RCPP
}
// fastMode
SEXP fastMode(SEXP x, bool narm);
RcppExport SEXP _DescToolsX_fastMode(SEXP xSEXP, SEXP narmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    rcpp_result_gen = Rcpp::wrap(fastMode(x, narm));
    return rcpp_result_gen;
END_RCPP
}
// fast_mode_cpp
SEXP fast_mode_cpp(SEXP x, bool narm);
RcppExport SEXP _DescToolsX_fast_mode_cpp(SEXP xSEXP, SEXP narmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_mode_cpp(x, narm));
    return rcpp_result_gen;
END_RCPP
}
// hlqest
double hlqest(NumericVector x);
RcppExport SEXP _DescToolsX_hlqest(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(hlqest(x));
    return rcpp_result_gen;
END_RCPP
}
// hl2qest
double hl2qest(NumericVector x, NumericVector y);
RcppExport SEXP _DescToolsX_hl2qest(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(hl2qest(x, y));
    return rcpp_result_gen;
END_RCPP
}
// hoeffdingD_cpp
double hoeffdingD_cpp(std::vector<unsigned long> perm);
RcppExport SEXP _DescToolsX_hoeffdingD_cpp(SEXP permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<unsigned long> >::type perm(permSEXP);
    rcpp_result_gen = Rcpp::wrap(hoeffdingD_cpp(perm));
    return rcpp_result_gen;
END_RCPP
}
// n_pow_sum_cpp
List n_pow_sum_cpp(NumericVector x);
RcppExport SEXP _DescToolsX_n_pow_sum_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(n_pow_sum_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// skew_cpp
double skew_cpp(NumericVector x, double mean);
RcppExport SEXP _DescToolsX_skew_cpp(SEXP xSEXP, SEXP meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    rcpp_result_gen = Rcpp::wrap(skew_cpp(x, mean));
    return rcpp_result_gen;
END_RCPP
}
// skew_weighted_cpp
double skew_weighted_cpp(NumericVector x, double mean, NumericVector w);
RcppExport SEXP _DescToolsX_skew_weighted_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(skew_weighted_cpp(x, mean, w));
    return rcpp_result_gen;
END_RCPP
}
// kurt_cpp
double kurt_cpp(NumericVector x, double mean);
RcppExport SEXP _DescToolsX_kurt_cpp(SEXP xSEXP, SEXP meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    rcpp_result_gen = Rcpp::wrap(kurt_cpp(x, mean));
    return rcpp_result_gen;
END_RCPP
}
// kurt_weighted_cpp
double kurt_weighted_cpp(NumericVector x, double mean, NumericVector w);
RcppExport SEXP _DescToolsX_kurt_weighted_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(kurt_weighted_cpp(x, mean, w));
    return rcpp_result_gen;
END_RCPP
}
// tbrm
double tbrm(const std::vector<double>& x, double C);
RcppExport SEXP _DescToolsX_tbrm(SEXP xSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(tbrm(x, C));
    return rcpp_result_gen;
END_RCPP
}
// tbrm_boot_cpp
NumericVector tbrm_boot_cpp(NumericVector x, int R, double alpha, double constant, int seed, String method);
RcppExport SEXP _DescToolsX_tbrm_boot_cpp(SEXP xSEXP, SEXP RSEXP, SEXP alphaSEXP, SEXP constantSEXP, SEXP seedSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type constant(constantSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(tbrm_boot_cpp(x, R, alpha, constant, seed, method));
    return rcpp_result_gen;
END_RCPP
}
// himed_weighted_cpp
double himed_weighted_cpp(NumericVector x, NumericVector w);
RcppExport SEXP _DescToolsX_himed_weighted_cpp(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(himed_weighted_cpp(x, w));
    return rcpp_result_gen;
END_RCPP
}
// himed_int_weighted_cpp
double himed_int_weighted_cpp(NumericVector x, IntegerVector iw);
RcppExport SEXP _DescToolsX_himed_int_weighted_cpp(SEXP xSEXP, SEXP iwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type iw(iwSEXP);
    rcpp_result_gen = Rcpp::wrap(himed_int_weighted_cpp(x, iw));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DescToolsX_assoc_cpp", (DL_FUNC) &_DescToolsX_assoc_cpp, 3},
    {"_DescToolsX_brier_boot_cpp", (DL_FUNC) &_DescToolsX_brier_boot_cpp, 4},
    {"_DescToolsX_condis_pairs_tab_cpp", (DL_FUNC) &_DescToolsX_condis_pairs_tab_cpp, 1},
    {"_DescToolsX_condis_pairs_xy_cpp", (DL_FUNC) &_DescToolsX_condis_pairs_xy_cpp, 2},
    {"_DescToolsX_cstat_boot_cpp", (DL_FUNC) &_DescToolsX_cstat_boot_cpp, 5},
    {"_DescToolsX_contcoef_table_boot_bca_cpp", (DL_FUNC) &_DescToolsX_contcoef_table_boot_bca_cpp, 5},
    {"_DescToolsX_contcoef_table_cpp", (DL_FUNC) &_DescToolsX_contcoef_table_cpp, 2},
    {"_DescToolsX_contcoef_table_boot_cpp", (DL_FUNC) &_DescToolsX_contcoef_table_boot_cpp, 4},
    {"_DescToolsX_isoWeek", (DL_FUNC) &_DescToolsX_isoWeek, 1},
    {"_DescToolsX_usWeek", (DL_FUNC) &_DescToolsX_usWeek, 1},
    {"_DescToolsX_isoYear", (DL_FUNC) &_DescToolsX_isoYear, 1},
    {"_DescToolsX_isoYearweek", (DL_FUNC) &_DescToolsX_isoYearweek, 1},
    {"_DescToolsX_usYearweek", (DL_FUNC) &_DescToolsX_usYearweek, 1},
    {"_DescToolsX_usYearmonth", (DL_FUNC) &_DescToolsX_usYearmonth, 1},
    {"_DescToolsX_isLeapYearDate", (DL_FUNC) &_DescToolsX_isLeapYearDate, 1},
    {"_DescToolsX_isLeapYearInt", (DL_FUNC) &_DescToolsX_isLeapYearInt, 1},
    {"_DescToolsX_top_n_cpp", (DL_FUNC) &_DescToolsX_top_n_cpp, 2},
    {"_DescToolsX_bottom_n_cpp", (DL_FUNC) &_DescToolsX_bottom_n_cpp, 2},
    {"_DescToolsX_top_i_cpp", (DL_FUNC) &_DescToolsX_top_i_cpp, 2},
    {"_DescToolsX_bottom_i_cpp", (DL_FUNC) &_DescToolsX_bottom_i_cpp, 2},
    {"_DescToolsX_fastMode", (DL_FUNC) &_DescToolsX_fastMode, 2},
    {"_DescToolsX_fast_mode_cpp", (DL_FUNC) &_DescToolsX_fast_mode_cpp, 2},
    {"_DescToolsX_hlqest", (DL_FUNC) &_DescToolsX_hlqest, 1},
    {"_DescToolsX_hl2qest", (DL_FUNC) &_DescToolsX_hl2qest, 2},
    {"_DescToolsX_hoeffdingD_cpp", (DL_FUNC) &_DescToolsX_hoeffdingD_cpp, 1},
    {"_DescToolsX_n_pow_sum_cpp", (DL_FUNC) &_DescToolsX_n_pow_sum_cpp, 1},
    {"_DescToolsX_skew_cpp", (DL_FUNC) &_DescToolsX_skew_cpp, 2},
    {"_DescToolsX_skew_weighted_cpp", (DL_FUNC) &_DescToolsX_skew_weighted_cpp, 3},
    {"_DescToolsX_kurt_cpp", (DL_FUNC) &_DescToolsX_kurt_cpp, 2},
    {"_DescToolsX_kurt_weighted_cpp", (DL_FUNC) &_DescToolsX_kurt_weighted_cpp, 3},
    {"_DescToolsX_tbrm", (DL_FUNC) &_DescToolsX_tbrm, 2},
    {"_DescToolsX_tbrm_boot_cpp", (DL_FUNC) &_DescToolsX_tbrm_boot_cpp, 6},
    {"_DescToolsX_himed_weighted_cpp", (DL_FUNC) &_DescToolsX_himed_weighted_cpp, 2},
    {"_DescToolsX_himed_int_weighted_cpp", (DL_FUNC) &_DescToolsX_himed_int_weighted_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DescToolsX(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
