// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ADstat
double ADstat(NumericVector x);
RcppExport SEXP _DescToolsX_ADstat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ADstat(x));
    return rcpp_result_gen;
END_RCPP
}
// ADtest
double ADtest(NumericVector x);
RcppExport SEXP _DescToolsX_ADtest(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ADtest(x));
    return rcpp_result_gen;
END_RCPP
}
// ADprobExactInf
NumericVector ADprobExactInf(NumericVector a);
RcppExport SEXP _DescToolsX_ADprobExactInf(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(ADprobExactInf(a));
    return rcpp_result_gen;
END_RCPP
}
// ADprobApproxInf
NumericVector ADprobApproxInf(NumericVector a);
RcppExport SEXP _DescToolsX_ADprobApproxInf(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(ADprobApproxInf(a));
    return rcpp_result_gen;
END_RCPP
}
// ADprobN
NumericVector ADprobN(NumericVector a, int n);
RcppExport SEXP _DescToolsX_ADprobN(SEXP aSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(ADprobN(a, n));
    return rcpp_result_gen;
END_RCPP
}
// ADtestR
Rcpp::List ADtestR(const Rcpp::NumericVector& x);
RcppExport SEXP _DescToolsX_ADtestR(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ADtestR(x));
    return rcpp_result_gen;
END_RCPP
}
// between_num
LogicalVector between_num(NumericVector x, NumericVector from, NumericVector to, bool left_closed, bool right_closed);
RcppExport SEXP _DescToolsX_between_num(SEXP xSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP left_closedSEXP, SEXP right_closedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< bool >::type left_closed(left_closedSEXP);
    Rcpp::traits::input_parameter< bool >::type right_closed(right_closedSEXP);
    rcpp_result_gen = Rcpp::wrap(between_num(x, from, to, left_closed, right_closed));
    return rcpp_result_gen;
END_RCPP
}
// acceptBin
double acceptBin(int x, int n, double p);
RcppExport SEXP _DescToolsX_acceptBin(SEXP xSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(acceptBin(x, n, p));
    return rcpp_result_gen;
END_RCPP
}
// binomdiffciMee
double binomdiffciMee(int x1, int n1, int x2, int n2, double alpha, bool lower);
RcppExport SEXP _DescToolsX_binomdiffciMee(SEXP x1SEXP, SEXP n1SEXP, SEXP x2SEXP, SEXP n2SEXP, SEXP alphaSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower(lowerSEXP);
    rcpp_result_gen = Rcpp::wrap(binomdiffciMee(x1, n1, x2, n2, alpha, lower));
    return rcpp_result_gen;
END_RCPP
}
// binomdiffciMN
double binomdiffciMN(int x1, int n1, int x2, int n2, double z, bool lower);
RcppExport SEXP _DescToolsX_binomdiffciMN(SEXP x1SEXP, SEXP n1SEXP, SEXP x2SEXP, SEXP n2SEXP, SEXP zSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< bool >::type lower(lowerSEXP);
    rcpp_result_gen = Rcpp::wrap(binomdiffciMN(x1, n1, x2, n2, z, lower));
    return rcpp_result_gen;
END_RCPP
}
// conv_DecToBin
CharacterVector conv_DecToBin(IntegerVector n);
RcppExport SEXP _DescToolsX_conv_DecToBin(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(conv_DecToBin(n));
    return rcpp_result_gen;
END_RCPP
}
// isoWeek
IntegerVector isoWeek(DateVector x);
RcppExport SEXP _DescToolsX_isoWeek(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(isoWeek(x));
    return rcpp_result_gen;
END_RCPP
}
// usWeek
IntegerVector usWeek(DateVector x);
RcppExport SEXP _DescToolsX_usWeek(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(usWeek(x));
    return rcpp_result_gen;
END_RCPP
}
// isoYear
IntegerVector isoYear(DateVector x);
RcppExport SEXP _DescToolsX_isoYear(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(isoYear(x));
    return rcpp_result_gen;
END_RCPP
}
// isoYearweek
IntegerVector isoYearweek(DateVector x);
RcppExport SEXP _DescToolsX_isoYearweek(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(isoYearweek(x));
    return rcpp_result_gen;
END_RCPP
}
// usYearweek
IntegerVector usYearweek(DateVector x);
RcppExport SEXP _DescToolsX_usYearweek(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(usYearweek(x));
    return rcpp_result_gen;
END_RCPP
}
// usYearmonth
IntegerVector usYearmonth(DateVector x);
RcppExport SEXP _DescToolsX_usYearmonth(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(usYearmonth(x));
    return rcpp_result_gen;
END_RCPP
}
// isLeapYearDate
IntegerVector isLeapYearDate(DateVector x);
RcppExport SEXP _DescToolsX_isLeapYearDate(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(isLeapYearDate(x));
    return rcpp_result_gen;
END_RCPP
}
// isLeapYearInt
IntegerVector isLeapYearInt(IntegerVector x);
RcppExport SEXP _DescToolsX_isLeapYearInt(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(isLeapYearInt(x));
    return rcpp_result_gen;
END_RCPP
}
// top_n
Rcpp::List top_n(Rcpp::NumericVector x, int n);
RcppExport SEXP _DescToolsX_top_n(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(top_n(x, n));
    return rcpp_result_gen;
END_RCPP
}
// bottom_n
Rcpp::List bottom_n(Rcpp::NumericVector x, int n);
RcppExport SEXP _DescToolsX_bottom_n(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(bottom_n(x, n));
    return rcpp_result_gen;
END_RCPP
}
// top_i
IntegerVector top_i(NumericVector v, unsigned int n);
RcppExport SEXP _DescToolsX_top_i(SEXP vSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(top_i(v, n));
    return rcpp_result_gen;
END_RCPP
}
// bottom_i
IntegerVector bottom_i(NumericVector v, unsigned int n);
RcppExport SEXP _DescToolsX_bottom_i(SEXP vSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(bottom_i(v, n));
    return rcpp_result_gen;
END_RCPP
}
// fastMode
SEXP fastMode(SEXP x, bool narm);
RcppExport SEXP _DescToolsX_fastMode(SEXP xSEXP, SEXP narmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    rcpp_result_gen = Rcpp::wrap(fastMode(x, narm));
    return rcpp_result_gen;
END_RCPP
}
// fastModeX
SEXP fastModeX(SEXP x, bool narm);
RcppExport SEXP _DescToolsX_fastModeX(SEXP xSEXP, SEXP narmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type narm(narmSEXP);
    rcpp_result_gen = Rcpp::wrap(fastModeX(x, narm));
    return rcpp_result_gen;
END_RCPP
}
// is_prime_u64
bool is_prime_u64(double x);
RcppExport SEXP _DescToolsX_is_prime_u64(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(is_prime_u64(x));
    return rcpp_result_gen;
END_RCPP
}
// primes_upto
IntegerVector primes_upto(int n);
RcppExport SEXP _DescToolsX_primes_upto(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(primes_upto(n));
    return rcpp_result_gen;
END_RCPP
}
// factor_u64
NumericMatrix factor_u64(double x);
RcppExport SEXP _DescToolsX_factor_u64(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(factor_u64(x));
    return rcpp_result_gen;
END_RCPP
}
// formatDateTime
CharacterVector formatDateTime(SEXP x, std::string fmt, bool strict, std::string locale);
RcppExport SEXP _DescToolsX_formatDateTime(SEXP xSEXP, SEXP fmtSEXP, SEXP strictSEXP, SEXP localeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type fmt(fmtSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< std::string >::type locale(localeSEXP);
    rcpp_result_gen = Rcpp::wrap(formatDateTime(x, fmt, strict, locale));
    return rcpp_result_gen;
END_RCPP
}
// formatNum
CharacterVector formatNum(NumericVector x, Nullable<IntegerVector> digits, Nullable<IntegerVector> ldigits, Nullable<CharacterVector> big_mark, Nullable<CharacterVector> decimal_mark, int sci_big, int sci_small);
RcppExport SEXP _DescToolsX_formatNum(SEXP xSEXP, SEXP digitsSEXP, SEXP ldigitsSEXP, SEXP big_markSEXP, SEXP decimal_markSEXP, SEXP sci_bigSEXP, SEXP sci_smallSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type digits(digitsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type ldigits(ldigitsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type big_mark(big_markSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type decimal_mark(decimal_markSEXP);
    Rcpp::traits::input_parameter< int >::type sci_big(sci_bigSEXP);
    Rcpp::traits::input_parameter< int >::type sci_small(sci_smallSEXP);
    rcpp_result_gen = Rcpp::wrap(formatNum(x, digits, ldigits, big_mark, decimal_mark, sci_big, sci_small));
    return rcpp_result_gen;
END_RCPP
}
// compute_LCM
long long compute_LCM(long long int a, long long int b);
RcppExport SEXP _DescToolsX_compute_LCM(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long long int >::type a(aSEXP);
    Rcpp::traits::input_parameter< long long int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_LCM(a, b));
    return rcpp_result_gen;
END_RCPP
}
// compute_GCD
long long compute_GCD(long long int a, long long int b);
RcppExport SEXP _DescToolsX_compute_GCD(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long long int >::type a(aSEXP);
    Rcpp::traits::input_parameter< long long int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_GCD(a, b));
    return rcpp_result_gen;
END_RCPP
}
// divs
IntegerVector divs(int x);
RcppExport SEXP _DescToolsX_divs(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(divs(x));
    return rcpp_result_gen;
END_RCPP
}
// hlqest
double hlqest(NumericVector x);
RcppExport SEXP _DescToolsX_hlqest(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(hlqest(x));
    return rcpp_result_gen;
END_RCPP
}
// hl2qest
double hl2qest(NumericVector x, NumericVector y);
RcppExport SEXP _DescToolsX_hl2qest(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(hl2qest(x, y));
    return rcpp_result_gen;
END_RCPP
}
// n_pow_sum
List n_pow_sum(NumericVector x);
RcppExport SEXP _DescToolsX_n_pow_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(n_pow_sum(x));
    return rcpp_result_gen;
END_RCPP
}
// roman2int_cpp
IntegerVector roman2int_cpp(CharacterVector x);
RcppExport SEXP _DescToolsX_roman2int_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(roman2int_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// rskew_cpp
double rskew_cpp(NumericVector x, double mean);
RcppExport SEXP _DescToolsX_rskew_cpp(SEXP xSEXP, SEXP meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    rcpp_result_gen = Rcpp::wrap(rskew_cpp(x, mean));
    return rcpp_result_gen;
END_RCPP
}
// rskeww_cpp
double rskeww_cpp(NumericVector x, double mean, NumericVector w);
RcppExport SEXP _DescToolsX_rskeww_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(rskeww_cpp(x, mean, w));
    return rcpp_result_gen;
END_RCPP
}
// rkurt_cpp
double rkurt_cpp(NumericVector x, double mean);
RcppExport SEXP _DescToolsX_rkurt_cpp(SEXP xSEXP, SEXP meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    rcpp_result_gen = Rcpp::wrap(rkurt_cpp(x, mean));
    return rcpp_result_gen;
END_RCPP
}
// rkurtw_cpp
double rkurtw_cpp(NumericVector x, double mean, NumericVector w);
RcppExport SEXP _DescToolsX_rkurtw_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(rkurtw_cpp(x, mean, w));
    return rcpp_result_gen;
END_RCPP
}
// tbrm
double tbrm(const std::vector<double>& x, double C);
RcppExport SEXP _DescToolsX_tbrm(SEXP xSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(tbrm(x, C));
    return rcpp_result_gen;
END_RCPP
}
// wgtHimed_cpp
double wgtHimed_cpp(NumericVector x, NumericVector w);
RcppExport SEXP _DescToolsX_wgtHimed_cpp(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(wgtHimed_cpp(x, w));
    return rcpp_result_gen;
END_RCPP
}
// wgtHimedInt_cpp
double wgtHimedInt_cpp(NumericVector x, IntegerVector iw);
RcppExport SEXP _DescToolsX_wgtHimedInt_cpp(SEXP xSEXP, SEXP iwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type iw(iwSEXP);
    rcpp_result_gen = Rcpp::wrap(wgtHimedInt_cpp(x, iw));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DescToolsX_ADstat", (DL_FUNC) &_DescToolsX_ADstat, 1},
    {"_DescToolsX_ADtest", (DL_FUNC) &_DescToolsX_ADtest, 1},
    {"_DescToolsX_ADprobExactInf", (DL_FUNC) &_DescToolsX_ADprobExactInf, 1},
    {"_DescToolsX_ADprobApproxInf", (DL_FUNC) &_DescToolsX_ADprobApproxInf, 1},
    {"_DescToolsX_ADprobN", (DL_FUNC) &_DescToolsX_ADprobN, 2},
    {"_DescToolsX_ADtestR", (DL_FUNC) &_DescToolsX_ADtestR, 1},
    {"_DescToolsX_between_num", (DL_FUNC) &_DescToolsX_between_num, 5},
    {"_DescToolsX_acceptBin", (DL_FUNC) &_DescToolsX_acceptBin, 3},
    {"_DescToolsX_binomdiffciMee", (DL_FUNC) &_DescToolsX_binomdiffciMee, 6},
    {"_DescToolsX_binomdiffciMN", (DL_FUNC) &_DescToolsX_binomdiffciMN, 6},
    {"_DescToolsX_conv_DecToBin", (DL_FUNC) &_DescToolsX_conv_DecToBin, 1},
    {"_DescToolsX_isoWeek", (DL_FUNC) &_DescToolsX_isoWeek, 1},
    {"_DescToolsX_usWeek", (DL_FUNC) &_DescToolsX_usWeek, 1},
    {"_DescToolsX_isoYear", (DL_FUNC) &_DescToolsX_isoYear, 1},
    {"_DescToolsX_isoYearweek", (DL_FUNC) &_DescToolsX_isoYearweek, 1},
    {"_DescToolsX_usYearweek", (DL_FUNC) &_DescToolsX_usYearweek, 1},
    {"_DescToolsX_usYearmonth", (DL_FUNC) &_DescToolsX_usYearmonth, 1},
    {"_DescToolsX_isLeapYearDate", (DL_FUNC) &_DescToolsX_isLeapYearDate, 1},
    {"_DescToolsX_isLeapYearInt", (DL_FUNC) &_DescToolsX_isLeapYearInt, 1},
    {"_DescToolsX_top_n", (DL_FUNC) &_DescToolsX_top_n, 2},
    {"_DescToolsX_bottom_n", (DL_FUNC) &_DescToolsX_bottom_n, 2},
    {"_DescToolsX_top_i", (DL_FUNC) &_DescToolsX_top_i, 2},
    {"_DescToolsX_bottom_i", (DL_FUNC) &_DescToolsX_bottom_i, 2},
    {"_DescToolsX_fastMode", (DL_FUNC) &_DescToolsX_fastMode, 2},
    {"_DescToolsX_fastModeX", (DL_FUNC) &_DescToolsX_fastModeX, 2},
    {"_DescToolsX_is_prime_u64", (DL_FUNC) &_DescToolsX_is_prime_u64, 1},
    {"_DescToolsX_primes_upto", (DL_FUNC) &_DescToolsX_primes_upto, 1},
    {"_DescToolsX_factor_u64", (DL_FUNC) &_DescToolsX_factor_u64, 1},
    {"_DescToolsX_formatDateTime", (DL_FUNC) &_DescToolsX_formatDateTime, 4},
    {"_DescToolsX_formatNum", (DL_FUNC) &_DescToolsX_formatNum, 7},
    {"_DescToolsX_compute_LCM", (DL_FUNC) &_DescToolsX_compute_LCM, 2},
    {"_DescToolsX_compute_GCD", (DL_FUNC) &_DescToolsX_compute_GCD, 2},
    {"_DescToolsX_divs", (DL_FUNC) &_DescToolsX_divs, 1},
    {"_DescToolsX_hlqest", (DL_FUNC) &_DescToolsX_hlqest, 1},
    {"_DescToolsX_hl2qest", (DL_FUNC) &_DescToolsX_hl2qest, 2},
    {"_DescToolsX_n_pow_sum", (DL_FUNC) &_DescToolsX_n_pow_sum, 1},
    {"_DescToolsX_roman2int_cpp", (DL_FUNC) &_DescToolsX_roman2int_cpp, 1},
    {"_DescToolsX_rskew_cpp", (DL_FUNC) &_DescToolsX_rskew_cpp, 2},
    {"_DescToolsX_rskeww_cpp", (DL_FUNC) &_DescToolsX_rskeww_cpp, 3},
    {"_DescToolsX_rkurt_cpp", (DL_FUNC) &_DescToolsX_rkurt_cpp, 2},
    {"_DescToolsX_rkurtw_cpp", (DL_FUNC) &_DescToolsX_rkurtw_cpp, 3},
    {"_DescToolsX_tbrm", (DL_FUNC) &_DescToolsX_tbrm, 2},
    {"_DescToolsX_wgtHimed_cpp", (DL_FUNC) &_DescToolsX_wgtHimed_cpp, 2},
    {"_DescToolsX_wgtHimedInt_cpp", (DL_FUNC) &_DescToolsX_wgtHimedInt_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DescToolsX(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
