
#' Frequency Table for a Single Variable
#' 
#' Calculates absolute and relative frequencies of a vector `x`.
#' Continuous (numeric) variables will be cut using the same logic as used by
#' the function [hist()]. Categorical variables will be aggregated by
#' [table()]. The result will contain single and cumulative
#' frequencies for both, absolute values and percentages.
#' 
#' By default only the valid cases are considered for the frequencies, say
#' `NA` values are excluded. (This is in accordance with the default
#' behavior of the R function `table`, which seemed a reasonable
#' reference.) If the `NA`s should be included you can set the
#' `useNA` argument to either `"ifany"` or `"always"`.
#' 
#' For numeric variables, if `breaks` is specified as a single number, the
#' range of the data is divided into breaks pieces of equal length, and then
#' the outer limits are moved away by 0.1\% of the range to ensure that the
#' extreme values both fall within the break intervals. (If `x` is a
#' constant vector, equal-length intervals are created that cover the single
#' value.) See [cut()].
#' 
#' With `breaks = FALSE` no classing takes place and the distinct values
#' of a numeric or date `x` are tabulated directly (in ascending order of
#' the values). In this case the `ord` argument applies as for categorical
#' variables.
#' 
#' @name freq
#' @aliases freq print.Freq
#' 
#' @param x variable to be described; may be any atomic type
#' @param breaks either a vector of two or more cut points or a single number
#' (greater than or equal to 2) giving the number of intervals into which x is
#' to be cut. For dates, a character interval specification accepted by
#' `cut.Date()`, such as `"days"`, `"weeks"`,
#' `"months"`, `"quarters"`, or `"years"`, can also be used.
#' For numeric variables, the default is taken from `hist()`; for dates,
#' calendar-aligned cut points are generated by `pretty()`. If set to
#' `FALSE`, a numeric or date `x` will not be classed at all, but
#' tabulated directly by its distinct values. This is useful for discrete
#' numeric variables such as counts or scores. The argument is ignored if x is
#' neither numeric nor a date.
#' @param include.lowest logical, indicating if an \verb{x[i]} equal to the lowest (or
#' highest, for `right = FALSE`) `"breaks"` value should be included.
#' Ignored if x is neither numeric nor a date, or if `breaks = FALSE`.
#' @param ord how should the result be ordered? Default is `"level"`,
#' other choices are 'by frequency' (`"desc"` or `"asc"`)
#' or 'by name of the levels' (`"name"`). The argument can be abbreviated.
#' This is ignored if x is numeric or a date and classed
#' (`breaks` not `FALSE`).
#' @param useNA one of `"no"`, `"ifany"`, or `"always"`.
#' Defines whether to include extra `NA` levels in the table.  Defaults to
#' `"no"` which is the [table()] default too.
#' @param \dots further arguments are passed to the function
#' [cut()]. Use `dig.lab` to control the format of numeric
#' group names. Use the argument `right` to define if the intervals should
#' be closed on the right (and open on the left) or vice versa. \cr In
#' `print.Freq` the dots are not used.
#' 
#' @return an object of class `"Freq"` inheriting from `data.frame`,
#' with columns:
#' \describe{
#'   \item{`level`}{levels or intervals of the tabulated variable}
#'   \item{`freq`}{absolute frequencies}
#'   \item{`perc`}{relative frequencies}
#'   \item{`cumfreq`}{cumulative absolute frequencies}
#'   \item{`cumperc`}{cumulative relative frequencies}
#' }
#' 
#' @examples
#' 
#' data(Pizza)
#' 
#' # result is a data.frame
#' d.freq <- freq(Pizza$price)
#' d.freq
#' 
#' # it is printed by default with 3 digits for the percent values,
#' # but the number of digits can be defined in the print function
#' print(d.freq, digits=5)
#' 
#' # sorted by frequency
#' freq(Pizza$driver, ord="desc")
#' 
#' # sorted by name using all the observations, say including NAs
#' freq(Pizza$driver, ord="name", useNA="ifany")
#' 
#' # percentages and cumulative frequencies for a vector of count data
#' freq(as.table(c(2,4,12,8)))
#' 
#' # tabulate a discrete numeric variable directly, without classing
#' freq(Pizza$count, breaks = FALSE)
#' 
#' # ... which also allows ordering by frequency
#' freq(Pizza$count, breaks = FALSE, ord = "desc")
#'
#' # dates are grouped using calendar-aligned default intervals
#' freq(as.Date("2025-01-01") + 0:99)
#' 
#' @seealso [cut()], [hist()], [cumsum()],
#' [table()], [prop.table()]
#' 
#' @family frequency
#' @concept frequency-table
#'
#' @rdname freq
#' @export
freq <- function(x,
                 breaks = if (isDate(x)) pretty(x) else hist(x, plot = FALSE)$breaks,
                 include.lowest = TRUE,
                 ord = c("level", "desc", "asc", "name"),
                 useNA = c("no", "ifany", "always"), ...){
  
  # check if x is a vector (do not use is.vector()!!!)
  if(!(is.atomic(x) || is.list(x))) stop("'x' must be a vector")
  
  if(inherits(x, "table")){
    tab <- x
    
  } else {
    
    if((is.numeric(x) || isDate(x)) && !isFALSE(breaks)){
      x <- cut(x, breaks = breaks, include.lowest = include.lowest,
               ordered_result = TRUE, ...)
    }
    
    tab <- table(x, useNA = useNA)
  }
  
  names(tab)[is.na(names(tab))] <- "<NA>"
  
  # how should the table be sorted, by name, level or frq? (NULL means "desc")
  switch(match.arg(ord, c("level", "desc", "asc", "name")),
         level  = {  }
           # tab[rownames(tab)] reindexed the table by its own names in
           # their existing order - a no-op. ord = "name" therefore did
           # exactly what ord = "level" does.
         , name   = { tab <- tab[order(names(tab))] }
         , asc    = { tab <- sort(tab) }
         , desc   = { tab <- -sort(-tab) }
  )
  
  ptab <- prop.table(tab)
  
  z <- data.frame(level = names(tab),
                  freq = as.vector(tab[]), perc = as.vector(ptab[]),
                  cumfreq = cumsum(tab[]), cumperc = cumsum(ptab[]))
  
  # the first class beyond 50% cumulative percentages is the median class
  attr(z, which = "medianclass") <- z[which(z[, 5]>=0.5)[1], 1]
  
  rownames(z) <- NULL # enumerate from 1:nrow(z)
  class(z) <- c("Freq", "data.frame")
  return(z)
  
}




#' @rdname freq
#' @method print Freq
#' @param digits number of digits used to display relative frequencies
#' @export
print.Freq <- function(x, digits = NULL, ...) {
  
  print.gap <- bedrock::getDotsArg(list(...), "print.gap", 2)
  
  # print as data.frame if something was changed
  if (ncol(x) != 5) {
    print.data.frame(x, digits = digits, ...)
  } else {
    
    afmt <- style("abs.sty")
    pfmt <- style("per.sty")
    
    if (!is.null(digits))
      pfmt$digits <- digits
    
    d.frm <- setNamesX(
      data.frame(
        x[,1],
        fm(x$freq, fmt = afmt),
        fm(x$perc, fmt = pfmt),
        fm(x$cumfreq, fmt = afmt),
        fm(x$cumperc, fmt = pfmt)
      ),
      colnames = names(x)
    )
    
    print(
      d.frm,
      print.gap = print.gap
    )
  }

  invisible(x)
}
