
#' Frequency Table for a Single Variable
#' 
#' Calculates absolute and relative frequencies of a vector \code{x}.
#' Continuous (numeric) variables will be cut using the same logic as used by
#' the function \code{\link{hist}}. Categorical variables will be aggregated by
#' \code{\link{table}}. The result will contain single and cumulative
#' frequencies for both, absolute values and percentages.
#' 
#' By default only the valid cases are considered for the frequencies, say
#' \code{NA} values are excluded. (This is in accordance with the default
#' behavior of the R function \code{table}, which seemed a reasonable
#' reference.) If the \code{NA}s should be included you can set the
#' \code{useNA} argument to either \code{"ifany"} or \code{"always"}.
#' 
#' For numeric variables, if \code{breaks} is specified as a single number, the
#' range of the data is divided into breaks pieces of equal length, and then
#' the outer limits are moved away by 0.1\% of the range to ensure that the
#' extreme values both fall within the break intervals. (If \code{x} is a
#' constant vector, equal-length intervals are created that cover the single
#' value.) See \code{\link{cut}}.
#' 
#' With \code{breaks = FALSE} no classing takes place and the distinct values
#' of a numeric or date \code{x} are tabulated directly (in ascending order of
#' the values). In this case the \code{ord} argument applies as for categorical
#' variables.
#' 
#' @name freq
#' @aliases freq print.Freq
#' 
#' @param x variable to be described; may be any atomic type
#' @param breaks either a vector of two or more cut points or a single number
#' (greater than or equal to 2) giving the number of intervals into which x is
#' to be cut. For dates, a character interval specification accepted by
#' \code{cut.Date()}, such as \code{"days"}, \code{"weeks"},
#' \code{"months"}, \code{"quarters"}, or \code{"years"}, can also be used.
#' For numeric variables, the default is taken from \code{hist()}; for dates,
#' calendar-aligned cut points are generated by \code{pretty()}. If set to
#' \code{FALSE}, a numeric or date \code{x} will not be classed at all, but
#' tabulated directly by its distinct values. This is useful for discrete
#' numeric variables such as counts or scores. The argument is ignored if x is
#' neither numeric nor a date.
#' @param include.lowest logical, indicating if an \verb{x[i]} equal to the lowest (or
#' highest, for \code{right = FALSE}) \code{"breaks"} value should be included.
#' Ignored if x is neither numeric nor a date, or if \code{breaks = FALSE}.
#' @param ord how should the result be ordered? Default is \code{"level"},
#' other choices are 'by frequency' (\code{"desc"} or \code{"asc"})
#' or 'by name of the levels' (\code{"name"}). The argument can be abbreviated.
#' This is ignored if x is numeric or a date and classed
#' (\code{breaks} not \code{FALSE}).
#' @param useNA one of \code{"no"}, \code{"ifany"}, or \code{"always"}.
#' Defines whether to include extra \code{NA} levels in the table.  Defaults to
#' \code{"no"} which is the \code{\link{table}()} default too.
#' @param \dots further arguments are passed to the function
#' \code{\link{cut}()}. Use \code{dig.lab} to control the format of numeric
#' group names. Use the argument \code{right} to define if the intervals should
#' be closed on the right (and open on the left) or vice versa. \cr In
#' \code{print.Freq} the dots are not used.
#' 
#' @return an object of class \code{"Freq"} inheriting from \code{data.frame},
#' with columns:
#' \describe{
#'   \item{\code{level}}{levels or intervals of the tabulated variable}
#'   \item{\code{freq}}{absolute frequencies}
#'   \item{\code{perc}}{relative frequencies}
#'   \item{\code{cumfreq}}{cumulative absolute frequencies}
#'   \item{\code{cumperc}}{cumulative relative frequencies}
#' }
#' 
#' @examples
#' 
#' data(Pizza)
#' 
#' # result is a data.frame
#' d.freq <- freq(Pizza$price)
#' d.freq
#' 
#' # it is printed by default with 3 digits for the percent values,
#' # but the number of digits can be defined in the print function
#' print(d.freq, digits=5)
#' 
#' # sorted by frequency
#' freq(Pizza$driver, ord="desc")
#' 
#' # sorted by name using all the observations, say including NAs
#' freq(Pizza$driver, ord="name", useNA="ifany")
#' 
#' # percentages and cumulative frequencies for a vector of count data
#' freq(as.table(c(2,4,12,8)))
#' 
#' # tabulate a discrete numeric variable directly, without classing
#' freq(Pizza$count, breaks = FALSE)
#' 
#' # ... which also allows ordering by frequency
#' freq(Pizza$count, breaks = FALSE, ord = "desc")
#'
#' # dates are grouped using calendar-aligned default intervals
#' freq(as.Date("2025-01-01") + 0:99)
#' 
#' @seealso \code{\link{cut}}, \code{\link{hist}}, \code{\link{cumsum}},
#' \code{\link{table}}, \code{\link{prop.table}}
#' 
#' @family frequency
#' @concept frequency-table
#'
#' @rdname freq
#' @export
freq <- function(x,
                 breaks = if (isDate(x)) pretty(x) else hist(x, plot = FALSE)$breaks,
                 include.lowest = TRUE,
                 ord = c("level", "desc", "asc", "name"),
                 useNA = c("no", "ifany", "always"), ...){
  
  # check if x is a vector (do not use is.vector()!!!)
  if(!(is.atomic(x) || is.list(x))) stop("'x' must be a vector")
  
  if(inherits(x, "table")){
    tab <- x
    
  } else {
    
    if((is.numeric(x) || isDate(x)) && !isFALSE(breaks)){
      x <- cut(x, breaks = breaks, include.lowest = include.lowest,
               ordered_result = TRUE, ...)
    }
    
    tab <- table(x, useNA = useNA)
  }
  
  names(tab)[is.na(names(tab))] <- "<NA>"
  
  # how should the table be sorted, by name, level or frq? (NULL means "desc")
  switch(match.arg(ord, c("level", "desc", "asc", "name")),
         level  = {  }
           # tab[rownames(tab)] reindexed the table by its own names in
           # their existing order - a no-op. ord = "name" therefore did
           # exactly what ord = "level" does.
         , name   = { tab <- tab[order(names(tab))] }
         , asc    = { tab <- sort(tab) }
         , desc   = { tab <- -sort(-tab) }
  )
  
  ptab <- prop.table(tab)
  
  z <- data.frame(level = names(tab),
                  freq = as.vector(tab[]), perc = as.vector(ptab[]),
                  cumfreq = cumsum(tab[]), cumperc = cumsum(ptab[]))
  
  # the first class beyond 50% cumulative percentages is the median class
  attr(z, which = "medianclass") <- z[which(z[, 5]>=0.5)[1], 1]
  
  rownames(z) <- NULL # enumerate from 1:nrow(z)
  class(z) <- c("Freq", "data.frame")
  return(z)
  
}




#' @rdname freq
#' @method print Freq
#' @param digits number of digits used to display relative frequencies
#' @export
print.Freq <- function(x, digits = NULL, ...) {
  
  print.gap <- bedrock::getDotsArg(list(...), "print.gap", 2)
  
  # print as data.frame if something was changed
  if (ncol(x) != 5) {
    print.data.frame(x, digits = digits, ...)
  } else {
    
    afmt <- style("abs.sty")
    pfmt <- style("per.sty")
    
    if (!is.null(digits))
      pfmt$digits <- digits
    
    d.frm <- setNamesX(
      data.frame(
        x[,1],
        fm(x$freq, fmt = afmt),
        fm(x$perc, fmt = pfmt),
        fm(x$cumfreq, fmt = afmt),
        fm(x$cumperc, fmt = pfmt)
      ),
      colnames = names(x)
    )
    
    print(
      d.frm,
      print.gap = print.gap
    )
  }

  invisible(x)
}
