# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assoc_cpp <- function(xR, yR, conf_level = 0.95) {
    .Call(`_DescToolsX_assoc_cpp`, xR, yR, conf_level)
}

brier_boot_cpp <- function(resp, pred, R, scaled) {
    .Call(`_DescToolsX_brier_boot_cpp`, resp, pred, R, scaled)
}

condis_pairs_tab_cpp <- function(x) {
    .Call(`_DescToolsX_condis_pairs_tab_cpp`, x)
}

condis_pairs_xy_cpp <- function(xR, yR) {
    .Call(`_DescToolsX_condis_pairs_xy_cpp`, xR, yR)
}

cstat_boot_cpp <- function(yR, xR, B = 1000L, alpha = 0.05, seed = -1L) {
    .Call(`_DescToolsX_cstat_boot_cpp`, yR, xR, B, alpha, seed)
}

contcoef_table_boot_bca_cpp <- function(tab, R, seed, correct, conf_level) {
    .Call(`_DescToolsX_contcoef_table_boot_bca_cpp`, tab, R, seed, correct, conf_level)
}

contcoef_table_cpp <- function(tab, correct = FALSE) {
    .Call(`_DescToolsX_contcoef_table_cpp`, tab, correct)
}

contcoef_table_boot_cpp <- function(tab, R = 5000L, seed = 0L, correct = FALSE) {
    .Call(`_DescToolsX_contcoef_table_boot_cpp`, tab, R, seed, correct)
}

isoWeek <- function(x) {
    .Call(`_DescToolsX_isoWeek`, x)
}

usWeek <- function(x) {
    .Call(`_DescToolsX_usWeek`, x)
}

isoYear <- function(x) {
    .Call(`_DescToolsX_isoYear`, x)
}

isoYearweek <- function(x) {
    .Call(`_DescToolsX_isoYearweek`, x)
}

usYearweek <- function(x) {
    .Call(`_DescToolsX_usYearweek`, x)
}

usYearmonth <- function(x) {
    .Call(`_DescToolsX_usYearmonth`, x)
}

isLeapYearDate <- function(x) {
    .Call(`_DescToolsX_isLeapYearDate`, x)
}

isLeapYearInt <- function(x) {
    .Call(`_DescToolsX_isLeapYearInt`, x)
}

top_n_cpp <- function(x, n = 5L) {
    .Call(`_DescToolsX_top_n_cpp`, x, n)
}

bottom_n_cpp <- function(x, n = 5L) {
    .Call(`_DescToolsX_bottom_n_cpp`, x, n)
}

top_i_cpp <- function(v, n) {
    .Call(`_DescToolsX_top_i_cpp`, v, n)
}

bottom_i_cpp <- function(v, n) {
    .Call(`_DescToolsX_bottom_i_cpp`, v, n)
}

fastMode <- function(x, narm = FALSE) {
    .Call(`_DescToolsX_fastMode`, x, narm)
}

fast_mode_cpp <- function(x, narm = FALSE) {
    .Call(`_DescToolsX_fast_mode_cpp`, x, narm)
}

lcm_cpp <- function(a, b) {
    .Call(`_DescToolsX_lcm_cpp`, a, b)
}

gcd_cpp <- function(a, b) {
    .Call(`_DescToolsX_gcd_cpp`, a, b)
}

divs <- function(x) {
    .Call(`_DescToolsX_divs`, x)
}

hlqest <- function(x) {
    .Call(`_DescToolsX_hlqest`, x)
}

hl2qest <- function(x, y) {
    .Call(`_DescToolsX_hl2qest`, x, y)
}

hoeffdingD_cpp <- function(perm) {
    .Call(`_DescToolsX_hoeffdingD_cpp`, perm)
}

n_pow_sum_cpp <- function(x) {
    .Call(`_DescToolsX_n_pow_sum_cpp`, x)
}

skew_cpp <- function(x, mean) {
    .Call(`_DescToolsX_skew_cpp`, x, mean)
}

skew_weighted_cpp <- function(x, mean, w) {
    .Call(`_DescToolsX_skew_weighted_cpp`, x, mean, w)
}

kurt_cpp <- function(x, mean) {
    .Call(`_DescToolsX_kurt_cpp`, x, mean)
}

kurt_weighted_cpp <- function(x, mean, w) {
    .Call(`_DescToolsX_kurt_weighted_cpp`, x, mean, w)
}

tbrm <- function(x, C) {
    .Call(`_DescToolsX_tbrm`, x, C)
}

himed_weighted_cpp <- function(x, w) {
    .Call(`_DescToolsX_himed_weighted_cpp`, x, w)
}

himed_int_weighted_cpp <- function(x, iw) {
    .Call(`_DescToolsX_himed_int_weighted_cpp`, x, iw)
}

