# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ADstat <- function(x) {
    .Call(`_DescToolsX_ADstat`, x)
}

ADtest <- function(x) {
    .Call(`_DescToolsX_ADtest`, x)
}

ADprobExactInf <- function(a) {
    .Call(`_DescToolsX_ADprobExactInf`, a)
}

ADprobApproxInf <- function(a) {
    .Call(`_DescToolsX_ADprobApproxInf`, a)
}

ADprobN <- function(a, n) {
    .Call(`_DescToolsX_ADprobN`, a, n)
}

ADtestR <- function(x) {
    .Call(`_DescToolsX_ADtestR`, x)
}

between_num <- function(x, from, to, left_closed = TRUE, right_closed = TRUE) {
    .Call(`_DescToolsX_between_num`, x, from, to, left_closed, right_closed)
}

acceptBin <- function(x, n, p) {
    .Call(`_DescToolsX_acceptBin`, x, n, p)
}

binomdiffciMee <- function(x1, n1, x2, n2, alpha, lower) {
    .Call(`_DescToolsX_binomdiffciMee`, x1, n1, x2, n2, alpha, lower)
}

binomdiffciMN <- function(x1, n1, x2, n2, z, lower) {
    .Call(`_DescToolsX_binomdiffciMN`, x1, n1, x2, n2, z, lower)
}

conv_DecToBin <- function(n) {
    .Call(`_DescToolsX_conv_DecToBin`, n)
}

isoWeek <- function(x) {
    .Call(`_DescToolsX_isoWeek`, x)
}

usWeek <- function(x) {
    .Call(`_DescToolsX_usWeek`, x)
}

isoYear <- function(x) {
    .Call(`_DescToolsX_isoYear`, x)
}

isoYearweek <- function(x) {
    .Call(`_DescToolsX_isoYearweek`, x)
}

usYearweek <- function(x) {
    .Call(`_DescToolsX_usYearweek`, x)
}

usYearmonth <- function(x) {
    .Call(`_DescToolsX_usYearmonth`, x)
}

isLeapYearDate <- function(x) {
    .Call(`_DescToolsX_isLeapYearDate`, x)
}

isLeapYearInt <- function(x) {
    .Call(`_DescToolsX_isLeapYearInt`, x)
}

top_n <- function(x, n = 5L) {
    .Call(`_DescToolsX_top_n`, x, n)
}

bottom_n <- function(x, n = 5L) {
    .Call(`_DescToolsX_bottom_n`, x, n)
}

top_i <- function(v, n) {
    .Call(`_DescToolsX_top_i`, v, n)
}

bottom_i <- function(v, n) {
    .Call(`_DescToolsX_bottom_i`, v, n)
}

fastMode <- function(x, narm = FALSE) {
    .Call(`_DescToolsX_fastMode`, x, narm)
}

fastModeX <- function(x, narm = FALSE) {
    .Call(`_DescToolsX_fastModeX`, x, narm)
}

is_prime_u64 <- function(x) {
    .Call(`_DescToolsX_is_prime_u64`, x)
}

primes_upto <- function(n) {
    .Call(`_DescToolsX_primes_upto`, n)
}

factor_u64 <- function(x) {
    .Call(`_DescToolsX_factor_u64`, x)
}

formatDateTime <- function(x, fmt, strict = TRUE, locale = "current") {
    .Call(`_DescToolsX_formatDateTime`, x, fmt, strict, locale)
}

formatNum <- function(x, digits = NULL, ldigits = NULL, big_mark = NULL, decimal_mark = NULL, sci_big = 9999L, sci_small = -9999L) {
    .Call(`_DescToolsX_formatNum`, x, digits, ldigits, big_mark, decimal_mark, sci_big, sci_small)
}

compute_LCM <- function(a, b) {
    .Call(`_DescToolsX_compute_LCM`, a, b)
}

compute_GCD <- function(a, b) {
    .Call(`_DescToolsX_compute_GCD`, a, b)
}

divs <- function(x) {
    .Call(`_DescToolsX_divs`, x)
}

hlqest <- function(x) {
    .Call(`_DescToolsX_hlqest`, x)
}

hl2qest <- function(x, y) {
    .Call(`_DescToolsX_hl2qest`, x, y)
}

n_pow_sum <- function(x) {
    .Call(`_DescToolsX_n_pow_sum`, x)
}

roman2int_cpp <- function(x) {
    .Call(`_DescToolsX_roman2int_cpp`, x)
}

rskew_cpp <- function(x, mean) {
    .Call(`_DescToolsX_rskew_cpp`, x, mean)
}

rskeww_cpp <- function(x, mean, w) {
    .Call(`_DescToolsX_rskeww_cpp`, x, mean, w)
}

rkurt_cpp <- function(x, mean) {
    .Call(`_DescToolsX_rkurt_cpp`, x, mean)
}

rkurtw_cpp <- function(x, mean, w) {
    .Call(`_DescToolsX_rkurtw_cpp`, x, mean, w)
}

tbrm <- function(x, C) {
    .Call(`_DescToolsX_tbrm`, x, C)
}

wgtHimed_cpp <- function(x, w) {
    .Call(`_DescToolsX_wgtHimed_cpp`, x, w)
}

wgtHimedInt_cpp <- function(x, iw) {
    .Call(`_DescToolsX_wgtHimedInt_cpp`, x, iw)
}

