# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

brier_boot_cpp <- function(resp, pred, R, scaled) {
    .Call(`_DescToolsX_brier_boot_cpp`, resp, pred, R, scaled)
}

coef_bootstrap_parallel_cpp <- function(X, y, B = 2000L, alpha = 0.05, seed = -1L) {
    .Call(`_DescToolsX_coef_bootstrap_parallel_cpp`, X, y, B, alpha, seed)
}

conDisPairsTab <- function(x) {
    .Call(`_DescToolsX_conDisPairsTab`, x)
}

cstat_bootstrap_parallel_cpp <- function(yR, xR, B = 1000L, alpha = 0.05, seed = -1L) {
    .Call(`_DescToolsX_cstat_bootstrap_parallel_cpp`, yR, xR, B, alpha, seed)
}

conDisPairsXY_ind_cpp <- function(xR, yR) {
    .Call(`_DescToolsX_conDisPairsXY_ind_cpp`, xR, yR)
}

bootstrap_contcoef_table_bca_cpp <- function(tab, R, seed, correct, conf_level) {
    .Call(`_DescToolsX_bootstrap_contcoef_table_bca_cpp`, tab, R, seed, correct, conf_level)
}

contcoef_table_cpp <- function(tab, correct = FALSE) {
    .Call(`_DescToolsX_contcoef_table_cpp`, tab, correct)
}

bootstrap_contcoef_table_cpp <- function(tab, R = 5000L, seed = 0L, correct = FALSE) {
    .Call(`_DescToolsX_bootstrap_contcoef_table_cpp`, tab, R, seed, correct)
}

isoWeek <- function(x) {
    .Call(`_DescToolsX_isoWeek`, x)
}

usWeek <- function(x) {
    .Call(`_DescToolsX_usWeek`, x)
}

isoYear <- function(x) {
    .Call(`_DescToolsX_isoYear`, x)
}

isoYearweek <- function(x) {
    .Call(`_DescToolsX_isoYearweek`, x)
}

usYearweek <- function(x) {
    .Call(`_DescToolsX_usYearweek`, x)
}

usYearmonth <- function(x) {
    .Call(`_DescToolsX_usYearmonth`, x)
}

isLeapYearDate <- function(x) {
    .Call(`_DescToolsX_isLeapYearDate`, x)
}

isLeapYearInt <- function(x) {
    .Call(`_DescToolsX_isLeapYearInt`, x)
}

top_n <- function(x, n = 5L) {
    .Call(`_DescToolsX_top_n`, x, n)
}

bottom_n <- function(x, n = 5L) {
    .Call(`_DescToolsX_bottom_n`, x, n)
}

top_i <- function(v, n) {
    .Call(`_DescToolsX_top_i`, v, n)
}

bottom_i <- function(v, n) {
    .Call(`_DescToolsX_bottom_i`, v, n)
}

fastMode <- function(x, narm = FALSE) {
    .Call(`_DescToolsX_fastMode`, x, narm)
}

fastModeX <- function(x, narm = FALSE) {
    .Call(`_DescToolsX_fastModeX`, x, narm)
}

compute_LCM <- function(a, b) {
    .Call(`_DescToolsX_compute_LCM`, a, b)
}

compute_GCD <- function(a, b) {
    .Call(`_DescToolsX_compute_GCD`, a, b)
}

divs <- function(x) {
    .Call(`_DescToolsX_divs`, x)
}

hlqest <- function(x) {
    .Call(`_DescToolsX_hlqest`, x)
}

hl2qest <- function(x, y) {
    .Call(`_DescToolsX_hl2qest`, x, y)
}

hoeffdingD_cpp <- function(perm) {
    .Call(`_DescToolsX_hoeffdingD_cpp`, perm)
}

n_pow_sum <- function(x) {
    .Call(`_DescToolsX_n_pow_sum`, x)
}

rsq_bootstrap_parallel_cpp <- function(X, y, B = 1000L, alpha = 0.05, adjusted = TRUE, seed = -1L) {
    .Call(`_DescToolsX_rsq_bootstrap_parallel_cpp`, X, y, B, alpha, adjusted, seed)
}

rskew_cpp <- function(x, mean) {
    .Call(`_DescToolsX_rskew_cpp`, x, mean)
}

rskeww_cpp <- function(x, mean, w) {
    .Call(`_DescToolsX_rskeww_cpp`, x, mean, w)
}

rkurt_cpp <- function(x, mean) {
    .Call(`_DescToolsX_rkurt_cpp`, x, mean)
}

rkurtw_cpp <- function(x, mean, w) {
    .Call(`_DescToolsX_rkurtw_cpp`, x, mean, w)
}

tbrm <- function(x, C) {
    .Call(`_DescToolsX_tbrm`, x, C)
}

wgtHimed_cpp <- function(x, w) {
    .Call(`_DescToolsX_wgtHimed_cpp`, x, w)
}

wgtHimedInt_cpp <- function(x, iw) {
    .Call(`_DescToolsX_wgtHimedInt_cpp`, x, iw)
}

